Create coinflip.cc.lua
yagpdb-cc/yagpdb-cc pull request #110
Opened 2020-11-30 12:37 UTC by DaviiD1337

2020-11-30 19:53 UTC, Jo3-L requested changes

2020-11-30 19:53 UTC, Jo3-L commented on fun/coinflip.cc.lua
> +	Joe L. <https://github.com/Jo3-L>
:cereal:

2020-12-01 19:50 UTC, Jo3-L commented
Please use the `.go.tmpl` file extension as of latest commit. Thanks!

2020-12-01 21:09 UTC, DaviiD1337 commented on fun/coinflip.cc.lua
> +	Joe L. <https://github.com/Jo3-L>
:cereal:

2020-12-02 01:02 UTC, merged

2020-12-02 01:02 UTC, Jo3-L commented
👌