Update rank.go.tmpl
yagpdb-cc/yagpdb-cc pull request #113
Opened 2020-12-02 10:26 UTC by JordiHakimZiyech

new PR, with updated code

2020-12-02 19:47 UTC, Jo3-L requested changes

2020-12-02 19:47 UTC, Jo3-L commented on leveling/rank.go.tmpl
> +{{ $rankbackground = ((dbGet .User.ID "background").Value) }} {{end}}
No way to set this currently, please remove or add a subcommand to set it (like how `set-color` is implemented).

2020-12-02 19:47 UTC, Jo3-L commented on leveling/rank.go.tmpl
> +	{{- end -}}
No need.
```suggestion
	{{ end }}
```

2020-12-02 19:47 UTC, Jo3-L commented on leveling/rank.go.tmpl
> +	{{- range $index, $entry := dbTopEntries "xp" 100 0 -}} {{/* Loop over top 100 entries - see if user is in top 100 */}}
No need.
```suggestion
	{{ range $index, $entry := dbTopEntries "xp" 100 0 }} {{- /* Loop over top 100 entries - see if user is in top 100 */}}
```

2020-12-02 19:47 UTC, Jo3-L commented on leveling/rank.go.tmpl
> +	{{- end -}}
No need.
```suggestion
	{{ end }}
```

2020-12-02 19:47 UTC, Jo3-L commented on leveling/rank.go.tmpl
> +{{ if not $rank }} {{ $rank = urlescape "100" }} {{ end }}
`100` is already url escaped.
Can also be onelined to this ->
```suggestion
{{ $rank = or $rank "100" }}
```

2020-12-02 22:21 UTC, JordiHakimZiyech commented
me did an oopsie, i copied to wrong command version lmao, should be fine right now

2020-12-05 00:01 UTC, Jo3-L requested changes
1) is this tested?
2) some general questions

2020-12-05 21:50 UTC, JordiHakimZiyech commented on leveling/rank.go.tmpl
> +						{{ end }}
my brain at 1am happened :thonk:

2020-12-06 20:08 UTC, merged

2020-12-06 20:08 UTC, Jo3-L commented
lgtm, thanks!