Create giveRoleAfterDelay
yagpdb-cc/yagpdb-cc pull request #126
Opened 2020-12-15 21:04 UTC by JordiHakimZiyech

gives role after delay cuz why not huh

2020-12-15 22:11 UTC, Jo3-L requested changes
maybe support cancelling giving the role and override past invocations using `scheduleUniqueCC` rather than `execCC`.

2020-12-15 22:11 UTC, Jo3-L commented on util/giveRoleAfterDelay
> + (carg "userid" "member to give role" )
`member` carg and access `User` field. `userid` doesn't validate.

2020-12-15 22:11 UTC, Jo3-L commented on util/giveRoleAfterDelay
> +{{ $search := slice .CmdArgs 2 | joinStr "" | lower }}
choose one and be consistent, `parseArgs` or manually parsing

2020-12-15 22:11 UTC, Jo3-L commented on util/giveRoleAfterDelay
> +{{ $a := (toDuration ($args.Get 1)).Seconds }}
no need, already a duration.

2020-12-15 22:11 UTC, Jo3-L commented on util/giveRoleAfterDelay
> +{{ execCC .CCID nil $a (sdict "user" ($args.Get 0) "role" ($args.Get 2)) }}
this won't work properly with fuzzy matching. Say user provides `foo` as their input role and the role that matches is `foobar`. `foo` is not the role name, `foobar` is, but you're using `foo`. Use role ID instead.

2020-12-15 22:11 UTC, Jo3-L commented on util/giveRoleAfterDelay
> +role has been given to <@{{$user}}> {{end}}
dunno if message should be sent after delay, especially if it's long and people forget

2020-12-16 07:27 UTC, JordiHakimZiyech commented
FRICK FILE NAME, SHIT

2020-12-26 10:59 UTC, closed without merging