Case System
yagpdb-cc/yagpdb-cc pull request #128
Opened 2020-12-18 03:17 UTC by Wolf-Maverick

Joe this a case system I made If you have any suggestions please do tell
And this is my first PR so no bully :(

2021-01-01 22:11 UTC, jo3-l2 requested changes
This currently seems to use 3 DB entries > case, can we change that to using 1 (sdict/dict entry) or even fewer?

2021-01-01 22:11 UTC, jo3-l2 commented on case system/cases.go.tmpl
> +{{- end -}}{{- end -}}
```suggestion
{{ range $cases }}
		{{- $value := str .Value }} 
		{{- $display = joinStr "" $display "\n" $value -}} 
{{ else }}
{{$display = "`No cases exist on this page`"}}
{{ end }}
```

2021-01-01 22:11 UTC, jo3-l2 commented on case system/viewcase.go.tmpl
> +	{{$channel = $a.Get "channel"}}
can all be transformed to the form `{{$a.Key}}` e.g. `$a.name`

2021-01-01 22:11 UTC, jo3-l2 commented on case system/viewcase.go.tmpl
> +{{with (dbGet $b "viewcase")}}
redundant, refactor please.

2021-01-01 22:11 UTC, jo3-l2 commented on case system/viewcase.go.tmpl
> +{{sendMessage nil "Could not find the case specified,Please make sure the case number is correct or the case has not been deleted"}}
```suggestion
Could not find the case specified,Please make sure the case number is correct or the case has not been deleted
```

2021-01-02 03:47 UTC, Maverick-Wolf commented
have resolved all the other issues, about the db thingy though of doing that, but the the current use of 3 db are a little easier to edit and its just 3 db entries so its okay  :) 
c'mon 3 is small

2021-01-21 17:46 UTC, MatiasMFM2001 commented
> c'mon 3 is small

Yup, but that needs more DB operations, which are costly (10 max). No idea if that also makes CC slower, due to LAGPDB

Using a single entry, you can fetch all data at once. Even with `dbTopEntries`/etc if you want to get a lot of entries to iterate them

2021-05-26 18:20 UTC, EsenDR commented
@Maverick-Wolf are you still working on this or do you plan to work on this? If not, maybe close this PR?

2021-05-27 02:50 UTC, closed without merging

2021-05-27 02:51 UTC, Maverick-Wolf commented
yeah will close this for now