added report system
yagpdb-cc/yagpdb-cc pull request #137
Opened 2020-12-29 22:35 UTC by Olde7325

This pull requests adds a report system, enhancing the native report command with additional functionalities.

## Summary
These CCs allow users to create a report system with the ability for their server members to request cancellation/nullification of their reports and adding some functionalities for staff utilizing reactions. All necessary information is arranged in an embed which is edited accordingly.

## Documentation
The system should be documented well enough for users with basic CC knowledge on how to add and set up this package.
Please take the time to read the documentation found in the README.md, as this is the crucial part for user accessibility and suggest possible changes.

## Stability
The code was tested thoroughly and should be stable, as long as the end user only changes the parts which are intended for changing. It might be slow from time to time, this is given by the amount of information YAGPDB puts together in the report message. 

Everything else is explained in the README file.

## Status
- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

---
This is my first PR to this repository. Thanks in advance!

2020-12-31 00:13 UTC, Jo3-L requested changes
initial review, just general code quality things, overall looks fine.

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +{{if not (ge (len .CmdArgs) 3)}}
```suggestion
{{if lt (len .CmdArgs) 3}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +            {{if eq (index .CmdArgs 1|str) $userKey}}
```suggestion
            {{if eq (index .CmdArgs 1) $userKey}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +                        {{.Set "Author" (sdict "name" (printf "%s (ID %d)" $user.String $user.ID) "icon_url" ($user.AvatarURL "256"))}}
```suggestion
                        {{.Set "Author" (sdict "name" (printf "%s (ID %d)" $user $user.ID) "icon_url" ($user.AvatarURL "256"))}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +                {{deleteMessage nil $response}}
```suggestion
                Your latest report was already cancelled! {{ deleteResponse }}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +{{deleteMessage nil $response}}{{else}}
```suggestion
Did not set regex to match Server Prefix! {{deleteTrigger}}{{deleteResponse}}
{{else}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +                {{deleteMessage nil $response}}
```suggestion
                Invalid key provided!
                {{deleteResponse}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/cancelReport.go.tmpl
> +            {{deleteMessage nil $response}}
```suggestion
            You are not the author of this report!
            {{deleteResponse}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/customReport.go.tmpl
> +            {{dbSet 2000 "reportSettings" (sdict "reportLog" (str $REPORT_LOG
Saving `sdict` to database preserves the original type. So you can consider not stringifying the IDs and using them directly.. just a thought.

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/customReport.go.tmpl
> +            {{sendMessage nil "**Database primed, report count reset, system is ready to use!**"}}
```suggestion
            **Database primed, report count reset, system is ready to use!**
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/customReport.go.tmpl
> +            {{sendMessage nil "You do not have permission to use this command!"}}
```suggestion
            You do not have permission to use this command!
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/customReport.go.tmpl
> +        {{deleteMessage nil $silly}}
```suggestion
        You can't report yourself, silly. {{deleteTrigger}} {{deleteResponse}}
```

2020-12-31 00:13 UTC, Jo3-L commented on moderation/reports/customReport.go.tmpl
> +        {{$logs250 := execAdmin "log" "250"}}
```suggestion
        {{$logs250 := execAdmin "log 250"}}
```

2020-12-31 00:31 UTC, Olde7325 commented
I will do these changes in one commit instead of committing each change individually, if that is fine?

2021-01-01 20:28 UTC, jo3-l2 approved these changes

2021-01-01 20:29 UTC, merged

2021-01-01 20:29 UTC, jo3-l2 commented
lgtm, thanks!

2021-01-01 20:43 UTC, Olde7325 commented
Thank you very much, as well! Have a happy new year 😄