Add new bigEmoji-v2.go.tmpl CC
yagpdb-cc/yagpdb-cc pull request #203
Opened 2021-05-20 17:14 UTC by dvoraknt

**Please describe the changes this PR makes and why it should be merged:**
Once again I have taken a simple command and made it overly complicated :ye: 

Stripped down and rebuilt the existing big emoji CC to increase feature set:
- base functionality retained (one emote -> image embed)
  - now provides emote name and image/gif direct link along with the image embed
- allow usage of message ID and link to scrape emotes from other messages
  - also supports pulling emotes from reactions with optional flag 
- support for up to 25 emotes per message (in either trigger or external message)
  - generates a list of emotes names with direct image links to each
- changed default emoji image provider to the official Twemoji repo
  - Twemoji is open source and free to use. I've included attribution per their specification at https://github.com/twitter/twemoji/blob/master/README.md#attribution-requirements, more specifically "We would consider a mention in the HTML/JS source sufficient also."
  - using the official Twemoji source should ensure that the image repo is consistently up to date with new emojis as they are released, repo currently has 1000+ more images available than the previous one
- due to number of potential operations and bot lag the CC can occasionally take a few seconds to complete, added a "loading" message to visually indicate that the CC is running
- clean looking embeds
- informative error messages

There can still be the rare issue with emoji images not existing on the image repo, I don't have a way to verify valid image links so have included a disclaimer in the "help" embed with a conditional footer pointing there when default emojis are queried.

**Status**

- [x] Code changes have been tested on an instance of YAGPDB, or there are no code changes
- [x] I have read and followed the [contribution guide](../CONTRIBUTING.md)

2021-05-20 17:28 UTC, l-zeuch commented
Ignore me, just gonna sneakily assign @jo3-l :ye:

2021-05-20 17:29 UTC, jo3-l commented on util/bigEmoji-v2.go.tmpl
> +			{{$msg = $subArg}}{{$chan = .H.e.n.l.o}}
what in the world is this

2021-05-20 17:36 UTC, BlackWolfWoof commented on util/bigEmoji-v2.go.tmpl
> +			{{$msg = $subArg}}{{$chan = .H.e.n.l.o}}
what in the world...

2021-05-25 23:09 UTC, l-zeuch requested changes
Couldn't find any big flukes, apart from this...

2021-05-25 23:09 UTC, l-zeuch commented on util/bigEmoji-v2.go.tmpl
> +			{{$msg = $subArg}}{{$chan = .H.e.n.l.o}}
```suggestion
			{{$msg = $subArg}}{{$chan = nil}}
```
Please....

2021-05-25 23:33 UTC, l-zeuch approved these changes
Awesome!

2021-05-25 23:34 UTC, merged

2021-05-25 23:34 UTC, l-zeuch commented
Thanks!